name: Example - Advanced Configuration

on:
  workflow_dispatch:
    inputs:
      quality:
        description: "JPEG quality (1-100)"
        required: false
        default: "85"
      convert-to:
        description: "Target format for conversion (jpg/png/webp)"
        required: false
        default: "jpg"

jobs:
  optimize-advanced:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Optimize Images (WebP Conversion)
        if: github.event.inputs.convert-to == 'webp'
        uses: hnrobert/git-image-preprocessor@v0.1.0
        with:
          quality: ${{ github.event.inputs.quality }}
          convert-to: webp
          max-width: 1920
          max-height: 1080
          commit-message: "🖼️ Optimize and convert images to WebP"
          max-size-kb: 2000
          skip-ci: false

      - name: Optimize Images (Standard)
        if: github.event.inputs.convert-to != 'webp'
        uses: hnrobert/git-image-preprocessor@v0.1.0
        with:
          quality: ${{ github.event.inputs.quality }}
          max-width: 2048
          max-height: 2048
          max-size-kb: 1000
          commit-message: "🖼️ Optimize images"
          file-patterns: "*.jpg *.jpeg *.png"
